__version__ = "1.1.1"

from meshroom.core import desc
from meshroomMicmac.custom import node

class SaisieMasqQT(node.MicmacNode):
    commandLine = 'mm3d SaisieMasqQT {filePathValue} {allParams}'
    documentation = '''SaisieMasqQT'''

    inputs = [
        desc.File(
            name='projectDirectory',
            label='Project Directory',
            description='Project Directory.',
            value="",
            group='', # required to execute mm3d command line
            uid=[0],
        ),
        desc.File(
            name='filePath',
            label='File Path',
            description='''Path of the file to open (image or PLY or camera XML).''',
            group='', # unnamed parameter
            value="",
            uid=[0],
        ),
        desc.BoolParam(
            name='setPostfix',
            label='Set Postfix',
            description="Set postfix.",
            uid=[0],
            value=False,
            group='',
            advanced=True,
        ),
        desc.StringParam(
            name='Post',
            label='File Postfix',
            description="Output file postfix.",
            enabled=lambda node: node.setPostfix.value,
            value="_Masq",
            uid=[0],
            advanced=True,
        ),
  #-----------modification-------------
        

        desc.BoolParam(
            name='setSzW',
            label='Set Window Size',
            description="Set name.",
            uid=[0],
            value=False,
            group='',
            advanced=True,
        ),

          
         desc.GroupAttribute(
            name='SzW',
            label='Window Size',
            description="set window size pixel",
            brackets='[]',
            joinChar=',',
            advanced=True,
            enabled=lambda node: node.setSzW.value,
            groupDesc=[
            desc.IntParam(
                name="width",
                label="Width",
                description="width.",
                value=900,
                range=(0,7680, 1),
                uid=[0],
            ),  
            
            desc.IntParam(
            name="height",
            label="Height",
            description="height.",
            value=600,
            range=(0, 4320 , 1),
            uid=[0],
            ),
        ]),
        
        
        
        
        #-----------modification-------------

        
        desc.BoolParam(
            name='setName',
            label='Set Name',
            description="Set name.",
            uid=[0],
            value=False,
            group='',
            advanced=True,
        ),
        desc.StringParam(
            name='Name',
            label='Name',
            description='''Set output filename (dafault=input+_Masq).''',
            enabled=lambda node: node.setName.value,
            value="",
            uid=[0],
            advanced=True,
        ),
        desc.BoolParam(
            name='setAttr',
            label='Set Attr',
            description="Set attr.",
            uid=[0],
            value=False,
            group='',
            advanced=True,
        ),
        desc.StringParam(
            name='Attr',
            label='Attr',
            description='''String to add to postfix..''',
            enabled=lambda node: node.setAttr.value,
            value="",
            uid=[0],
            advanced=True,
        ),
        desc.BoolParam(
            name='setGamma',
            label='Set Gamma',
            description="Set gamma.",
            uid=[0],
            value=False,
            group='',
            advanced=True,
        ),
        desc.FloatParam(
            name='Gama',
            label='Gamma',
            description='Apply gamma to image.',
            enabled=lambda node: node.setGamma.value,
            value=1.5,
            range=(1.0, 4.0, 0.01),
            uid=[0],
            advanced=True,
        ),
    ]

  #-----------modification-------------
    outputs = [
      
        desc.File(
            name='outputFile',
            label='Output File',
            description='''Path to the output file generated by SaisieMasqQT.''',
            group='', # unnamed parameter
            value= '{nameoutputFileValue}',
            uid=[0],
           
        ),
    ]

    
    

    

    @classmethod
    def update(cls, node):

        if '.' in node.filePath.value and '.' not in node.Name.value :
            node.nameoutputFile.value = node.filePath.value.split(".")[0] + node.Post.value + node.Attr.value+".xml"
         
        else :
            node.nameoutputFile.value = str(node.Name.value)
        

  #-----------modification-------------
